import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { useUser, SignInButton } from "@clerk/nextjs";

// import components
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <>
      <div className="flex w-full gap-3">
        <Image
          src={user.profileImageUrl}
          alt="Profile Image"
          className="h-16 w-16 rounded-full"
          width={56}
          height={56}
        />
        <input
          placeholder="Type things!"
          className="grow bg-transparent outline-none"
        />
      </div>
    </>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <>
      <div className="flex items-center gap-3 border-b border-slate-400 p-4">
        <Image
          src={author.profilePicture}
          alt="Profile Picture"
          className="h-16 w-16 rounded-full"
          width={56}
          height={56}
        />
        <div className="flex flex-col">
          <div className="flex gap-1 text-slate-400">
            <span>{`@${author.username} `}</span>
            <span className="font-thin">{` · ${dayjs(
              post.createdAt
            ).fromNow()}`}</span>
          </div>
          {post.content}
        </div>
      </div>
    </>
  );
};

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();

  const user = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>No Data...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {user.isSignedIn ? <CreatePostWizard /> : <SignInButton />}
          </div>
          <div className="flex flex-col">
            {[...data]?.map((fullPost) => {
              return <PostView key={fullPost.post.id} {...fullPost} />;
            })}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
